In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense
from tensorflow.keras.preprocessing.text import Tokenizer

/Users/ajitesh/Desktop/AI_ML_Learn/.venv/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/attr_value.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/Users/ajitesh/Desktop/AI_ML_Learn/.venv/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/Users/ajitesh/Desktop/AI_ML_Learn/.venv/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/resour

In [2]:
tokenizer= Tokenizer( oov_token="<OOV>") # out of vocabulary token

In [3]:
docs=[
    "I love programming in Python",
    "Python is great for data science",
    "I enjoy learning new programming languages",
    "Data science is an exciting field",
    "I love solving problems with Python",
    "Python is versatile and powerful",
    "I enjoy building machine learning models",
    "Data science involves statistics and programming",
    "I love exploring new technologies",
]

tokenizer.fit_on_texts(docs)
word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(docs)

print("Tokenized Documents:", tokenizer.texts_to_sequences(docs))
print("Word Index:", word_index)
print("Sequences:", sequences)


Tokenized Documents: [[2, 4, 5, 13, 3], [3, 6, 14, 15, 7, 8], [2, 9, 10, 11, 5, 16], [7, 8, 6, 17, 18, 19], [2, 4, 20, 21, 22, 3], [3, 6, 23, 12, 24], [2, 9, 25, 26, 10, 27], [7, 8, 28, 29, 12, 5], [2, 4, 30, 11, 31]]
Word Index: {'<OOV>': 1, 'i': 2, 'python': 3, 'love': 4, 'programming': 5, 'is': 6, 'data': 7, 'science': 8, 'enjoy': 9, 'learning': 10, 'new': 11, 'and': 12, 'in': 13, 'great': 14, 'for': 15, 'languages': 16, 'an': 17, 'exciting': 18, 'field': 19, 'solving': 20, 'problems': 21, 'with': 22, 'versatile': 23, 'powerful': 24, 'building': 25, 'machine': 26, 'models': 27, 'involves': 28, 'statistics': 29, 'exploring': 30, 'technologies': 31}
Sequences: [[2, 4, 5, 13, 3], [3, 6, 14, 15, 7, 8], [2, 9, 10, 11, 5, 16], [7, 8, 6, 17, 18, 19], [2, 4, 20, 21, 22, 3], [3, 6, 23, 12, 24], [2, 9, 25, 26, 10, 27], [7, 8, 28, 29, 12, 5], [2, 4, 30, 11, 31]]


In [4]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post',value=-1)
print("Padded Sequences:", sequences)

Padded Sequences: [[ 2  4  5 13  3 -1]
 [ 3  6 14 15  7  8]
 [ 2  9 10 11  5 16]
 [ 7  8  6 17 18 19]
 [ 2  4 20 21 22  3]
 [ 3  6 23 12 24 -1]
 [ 2  9 25 26 10 27]
 [ 7  8 28 29 12  5]
 [ 2  4 30 11 31 -1]]


In [5]:
model = Sequential()
model.add(SimpleRNN(3, input_shape=(4, 5)))
model.add(Dense(1,activation='sigmoid'))

model.summary()

/Users/ajitesh/Desktop/AI_ML_Learn/.venv/lib/python3.13/site-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 3)              │            27 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Prepare X_train and y_train
X_train = sequences
y_train = np.random.randint(0, 2, size=(len(X_train),))  # Dummy binary labels

model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

NameError: name 'X_train' is not defined